all: serveur1-ServiamIndeclinabilem.py serveur2-ServiamIndeclinabilem.py
	@echo '#!/usr/bin/python3\n' > ../bin/serveur1-ServiamIndeclinabilem
	@cat serveur1-ServiamIndeclinabilem.py >> ../bin/serveur1-ServiamIndeclinabilem
	@chmod 777 ../bin/serveur1-ServiamIndeclinabilem
	
	@echo '#!/usr/bin/python3\n' > ../bin/serveur2-ServiamIndeclinabilem
	@cat serveur2-ServiamIndeclinabilem.py >> ../bin/serveur2-ServiamIndeclinabilem
	@chmod 777 ../bin/serveur2-ServiamIndeclinabilem

	@echo '#!/usr/bin/python3\n' > ../bin/serveur3-ServiamIndeclinabilem
	@cat serveur3-ServiamIndeclinabilem.py >> ../bin/serveur3-ServiamIndeclinabilem
	@chmod 777 ../bin/serveur3-ServiamIndeclinabilem

clean:
	@rm -f ../bin/*
    